# Generated by Django 2.0.2 on 2018-02-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180204_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
